"""Render `docs/api.md` from the package itself.

A hand-written API page is a page that is wrong three commits later. This one
is generated from `fz.__all__` by introspection -- every signature and every
summary line is read off the live objects -- and `tests/test_api_docs.py`
regenerates it under pytest and demands the committed file match character for
character. Rename a parameter without regenerating and CI goes red.

    python3 tools/gen_api_docs.py            # write docs/api.md
    python3 tools/gen_api_docs.py --check    # exit 1 if it is stale
"""

from __future__ import annotations

import dataclasses
import inspect
import pathlib
import sys

import fz

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "api.md"

#: Section order and the one-line description of each module, mirroring the
#: "What's inside" table in README.md.
SECTIONS: list[tuple[str, str, str]] = [
    ("fz.universe", "Universe",
     "The synthetic panel, and the `premia=` override that builds placebos."),
    ("fz.loaders", "Loaders",
     "The same `Universe`, built from your own prices instead."),
    ("fz.factors", "Characteristics",
     "Per-date winsorise, then per-date z-score. Shape in, shape out."),
    ("fz.portfolio", "Portfolio sorts",
     "Quantile ladders, the long-short leg, and what it compounds to."),
    ("fz.crossect", "Cross-sectional estimation",
     "Fama-MacBeth, its standard errors, and the information coefficient."),
]

HEADER = """<!-- Generated by tools/gen_api_docs.py. Do not edit by hand:
     tests/test_api_docs.py regenerates this page and fails if it has drifted
     from the code. Run `make docs` (or `python3 tools/gen_api_docs.py`). -->

# API reference

Everything `fz` exports, with the signature it actually has. Prose lives in
[theory.md](theory.md) and [validation.md](validation.md); worked examples live
in the docstrings themselves, and are run as doctests by the test suite.

Every panel argument and every returned score is `(n_days, n_stocks)`, NaN
where a value is not yet knowable.
"""


def _summary(obj) -> str:
    """First paragraph of a docstring, collapsed to one line."""
    doc = inspect.getdoc(obj) or ""
    para: list[str] = []
    for line in doc.splitlines():
        if not line.strip():
            break
        para.append(line.strip())
    return " ".join(para)


def _signature(name: str, obj) -> str:
    if dataclasses.is_dataclass(obj):
        fields = ", ".join(f.name for f in dataclasses.fields(obj))
        return f"class {name}({fields})"
    try:
        # eval_str resolves the string annotations `from __future__ import
        # annotations` leaves behind, so the page shows `int`, not `'int'`.
        return f"{name}{inspect.signature(obj, eval_str=True)}"
    except (TypeError, ValueError):  # pragma: no cover - no such export today
        return name


def render() -> str:
    exported = [n for n in fz.__all__ if not n.startswith("__")]
    seen: set[str] = set()
    out = [HEADER]

    for module, title, blurb in SECTIONS:
        names = [n for n in exported
                 if getattr(getattr(fz, n), "__module__", None) == module]
        # Constants (DEFAULT_PREMIA) carry no __module__; place them by lookup.
        names += [n for n in exported
                  if n not in names and not hasattr(getattr(fz, n), "__module__")
                  and hasattr(sys.modules[module], n)]
        if not names:  # pragma: no cover - every section has exports today
            continue
        out.append(f"## {title}\n\n{blurb}\n")
        for name in names:
            seen.add(name)
            obj = getattr(fz, name)
            if isinstance(obj, dict):
                # A dict has no useful docstring of its own; print its contents,
                # which cannot go stale.
                items = ", ".join(f"`{k}` = {v:g}" for k, v in obj.items())
                out.append(f"### `{name}`\n\nWhat `make_universe` writes into the "
                           f"panel unless `premia=` overrides it: {items}.\n")
                continue
            out.append(f"### `{_signature(name, obj)}`\n\n{_summary(obj)}\n")

    missing = [n for n in exported if n not in seen]
    if missing:
        raise SystemExit(f"exports missing from a section: {missing}")
    out.append(f"---\n\n`fz.__version__` is `{fz.__version__}`; "
               f"`fz.__all__` has {len(exported)} names, all listed above.\n")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run: python3 {__file__}")
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
